// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3tZ0nmi0EVbMgb3siz_-2uoT5r7d65s',
    appId: '1:134544866208:android:97f31f89809c33aa0182c5',
    messagingSenderId: '134544866208',
    projectId: 'new-chat-app-c61aa',
    databaseURL: 'https://new-chat-app-c61aa-default-rtdb.firebaseio.com',
    storageBucket: 'new-chat-app-c61aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzzS1kHtxq0U8kJvZz7Mrh0_0LUx6hgE',
    appId: '1:134544866208:ios:2035da2895cc2df40182c5',
    messagingSenderId: '134544866208',
    projectId: 'new-chat-app-c61aa',
    databaseURL: 'https://new-chat-app-c61aa-default-rtdb.firebaseio.com',
    storageBucket: 'new-chat-app-c61aa.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );
}
